---
name: docker_image_building
kind: pipeline
type: docker

steps:
- name: build plugin 
  image: registry.nextpertise.tools/nextpertise-proxy/library/maven:3.8.7-openjdk-18
  depends_on:
    - clone
  command: clean install

image_pull_secrets:
  - platform_harbor_pull_secrets
